Update gcc information
UoGSOCIS/uogsocis.github.io pull request #118
Opened 2020-10-10 01:31 UTC by BenPearo

I added the new meeting date, the zoom link (Nathan okayed this), and a link to the new 2020 submission form (Nathan wasn't able to provide a new embeddable link).

2020-10-12 02:47 UTC, keeferrourke commented on gcc/index.html
> +        The Guelph Coding Community has been organizing student run Tech Talks since 2013. GCC talks are currently being held every Thursday night at 5:30pm over Zoom. Check our social media for info
I'm worried that leaving the `?pwd` parameter on this URL will leave us open to spammers who join random Zoom links.
Can we instead include the meeting passcode in the page?

2020-10-12 02:47 UTC, keeferrourke requested changes
LGTM, except I don't think the Zoom meeting password should be left on the URL.

2020-10-14 14:38 UTC, BenPearo reviewed
Removed the password, and added some text suggesting to check our socials for the code

2020-10-14 16:01 UTC, keeferrourke approved these changes

2020-10-14 16:02 UTC, merged