Beginning of major redesign
UoGSOCIS/uogsocis.github.io pull request #123
Opened 2021-03-29 00:17 UTC by BenPearo

Includes many unfinished pages, but has the architecture for the new clubs page and event cards. This branch will serve to let students contribute the the redesign without storing breaking changes on the main branch.

2021-03-29 16:05 UTC, keeferrourke requested changes

2021-03-29 16:05 UTC, keeferrourke commented on _layouts/club.html
> +                    <!-- pictures? -->
what's up with these comments?

2021-03-29 16:05 UTC, keeferrourke commented on _includes/header.html
> +            <li><a href="/clubs/">Clubs</a></li>
The plan is to turn this into a drop-down menu with options for each of the SOCCSOs, correct?

2021-03-29 16:05 UTC, keeferrourke commented on _posts/clubs/2021-03-28-socis.md
> +---
This is so clean! :heart:  :sparkles:

2021-03-29 16:05 UTC, keeferrourke commented on _posts/clubs/2021-03-28-socis.md
> +    - {name: Sara Adi, position: First Year Representative, email: first-year-rep@socis.ca}
These emails are wrong. I think you should have:

- `first-year-rep@socis.ca`
- `student-rep2@socis.ca`
- `student-rep3@socis.ca`
- `student-rep4@socis.ca`

2021-03-29 16:05 UTC, keeferrourke commented on _posts/clubs/2021-03-28-socis.md
> +    - {name: Sara Adi, position: First Year Representative, email: first-year-rep@socis.ca}
Also Sara is here 3 times! @BenPearo put yourself and Miranda on lines 18 and 19.

2021-03-29 16:15 UTC, keeferrourke commented on clubs/index.html
> +<div class="container">
How do I preview this page?

visiting `localhost:4000/clubs` is a 404. Am I missing something?

2021-03-30 02:01 UTC, BenPearo commented on _layouts/club.html
> +    <meta content="Computer Science We are a group of computer science students for computer science students. We coordinate with the School of Computer Science in …" name="description">
Good idea. This is on all our pages so I will do that

2021-03-30 02:01 UTC, BenPearo commented on _posts/events/2021-02-10-prose-file.md
> +Wow prose is sweet
correct will remove

2021-03-30 02:01 UTC, BenPearo commented on _includes/club-card.html
> +<article>
yep

2021-03-30 02:01 UTC, BenPearo commented on _layouts/club.html
> +                    <!-- pictures? -->
Oh I should remove those

2021-03-30 02:02 UTC, BenPearo commented on _includes/header.html
> +            <li><a href="/clubs/">Clubs</a></li>
I was planning on making a sort of club homepage. A dropdown would mean we don't have to make cards for clubs which is an idea I like

2021-03-30 02:03 UTC, BenPearo commented on _posts/clubs/2021-03-28-socis.md
> +    - {name: Sara Adi, position: First Year Representative, email: first-year-rep@socis.ca}
Thank you! I was waiting for confirmation in slack but sent it through

2021-03-30 02:03 UTC, BenPearo commented on clubs/index.html
> +<div class="container">
The clubs tab at the top should navigate you there

2021-03-30 15:46 UTC, keeferrourke commented on _includes/header.html
> +            <li><a href="/clubs/">Clubs</a></li>
Okay cool, a club homepage is better :)

2021-03-30 15:48 UTC, keeferrourke commented on clubs/index.html
> +<div class="container">
Hm I don't see a clubs tab? 

![image](https://user-images.githubusercontent.com/6888381/113017734-50ec6880-916f-11eb-8ce9-f7e6f5d525c3.png)

![image](https://user-images.githubusercontent.com/6888381/113017793-619cde80-916f-11eb-94b7-a0303c47e368.png)

2021-04-02 18:15 UTC, BenPearo reviewed
All requested changes have been made. Please test locally before approving.

2021-04-05 13:21 UTC, keeferrourke commented on clubs/index.html
> +<div class="container">
Ha yeah my bad :sweat:

2021-04-05 13:22 UTC, keeferrourke approved these changes

2021-04-06 12:41 UTC, merged